### PR TITLE
Fix add remove volumes

### LINKED ISSUE #21: new volumes are not replicated
While declaring new btrfs volumes in docker-compose they are not replicate to the next deployment.

making potential data lost. While this issue is open add/remove the missing/extra volume in the kv/store manually after deployment.

### PR DESCRIPTION
**Pull request by petrus-v**
tested by https://github.com/mlfmonde/cluster_lab/pull/7

fix #21 and #22

(First commit is about cleanup hapx template, I can make do it in an other PR If you prefer)

### CODE REVIEW

**Comment by ccomb** [comment]
LGTM for me,
just one thing : I would suggest to rename `event_it` to `deploy_id` everywhere, because there is no such thing as an "event" in the Application object, but just a deployment number (the notion of event only exists upstream in Consul).  This would be consistent with the `deploy_date` argument in the `_path()` function with (`deploy_date`, `deploy_id`) args

**Comment by ccomb** [comment]
One question, how to you manage transition with the already deployed apps?

**Comment by petrus-v** [comment]
@ccomb 

- Good idea I gonna rename ``event_id`` to ``deploy_id``.
- Transition should be transparent for users as tested [here](https://github.com/mlfmonde/cluster/pull/24/files#diff-b661c8827bf41471eb6672517d1d424bR1331) you can see that oldapp which is initialized from k/v store get the same path as ``app`` which would be set before this evolution without event_id/deploy_id. In other words if there are no event_id/deploy_id in k/v store system will fallbacks to the deploy_date to generate the path.

regards,

**Comment by petrus-v** [comment]
merging myself after @ccomb reviews and test passed against https://github.com/mlfmonde/cluster_lab/pull/7

**Pull request merged**
